import { Colors } from '../render/Colors.js';

export const TileTypes = {
    '.': {
        name: 'floor',
        glyph: '.',
        fg: Colors.floorLit,
        bg: null,
        blocksMove: false,
        blocksSight: false,
        fgExplored: Colors.floor,
    },
    '#': {
        name: 'wall',
        glyph: '#',
        fg: Colors.wall,
        bg: Colors.wallBg,
        blocksMove: true,
        blocksSight: true,
        fgExplored: '#3a3a34',
        bgExplored: '#0f0f0c',
    },
    '+': {
        name: 'closed_door',
        glyph: '+',
        fg: Colors.door,
        bg: Colors.doorBg,
        blocksMove: true,
        blocksSight: true,
        fgExplored: '#6a5028',
        bgExplored: '#0f0a04',
        interactable: true,
    },
    '/': {
        name: 'open_door',
        glyph: '/',
        fg: Colors.door,
        bg: null,
        blocksMove: false,
        blocksSight: false,
        fgExplored: '#6a5028',
    },
    '%': {
        name: 'rubble',
        glyph: '%',
        fg: Colors.rubble,
        bg: null,
        blocksMove: false,
        blocksSight: false,
        fgExplored: '#3a3020',
        moveCost: 2,
    },
    '~': {
        name: 'water',
        glyph: '~',
        fg: Colors.water,
        bg: Colors.waterBg,
        blocksMove: true,
        blocksSight: false,
        fgExplored: '#1a3050',
        bgExplored: '#050a12',
    },
    'o': {
        name: 'barrel',
        glyph: 'o',
        fg: Colors.barrel,
        bg: null,
        blocksMove: true,
        blocksSight: false,
        fgExplored: '#4a3a18',
        providesHalfCover: true,
    },
};
